databases:
  - name: blog-db
    plan: free
    databaseName: blog-db
    user: abeni

services:
  - type: web
    plan: free
    name: blog-app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn blog_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
